server:
 port: 8080

 
spring:
   cloud:
     gateway:
       routes:

            
         - id: aportacion-service
           uri: http://aportacion-service:8080
           predicates:
            - Path=/open/**

         - id: first-service
           uri: http://first-service:8080
           predicates:
            - Path=/first/**
            
         - id: angular-service
           uri: http://angular-service:8080
           predicates:
            - Path=/**    
   httpclient:
      connect-timeout: 1000
      response-timeout: 55s
