server:
 port: 8080

 
spring:
   cloud:
     gateway:
       routes:
         - id: GAFF-SESSION-SERVICE
           uri: http://localhost:8081
           predicates:
            - Path=/gaff/session-control/**
            
         - id: aportacion-service
           uri: http://aportacion-service:8080
           predicates:
            - Path=/**
            
       
   httpclient:
      connect-timeout: 1000
      response-timeout: 55s
