server:
 port: 8080

 
spring:
   cloud:
     gateway:
       routes:

            
         - id: aportacion-service
           uri: http://aportacion-service:8080
           predicates:
            - Path=/open/**

         - id: usuario-service
           uri: http://usuario-service:8080
           predicates:
            - Path=/usuario/**
            
         - id: angular-service
           uri: http://angular-service:8080
           predicates:
            - Path=/**    
   httpclient:
      connect-timeout: 1000
      response-timeout: 55s
