server:
 port: 8080

 
spring:
   cloud:
     gateway:
       routes:
         - id: GAFF-SESSION-SERVICE
           uri: http://angular-service:8080
           predicates:
            - Path=/front
           filters:
            - RedirectTo=302, http://angular-service:8080
            
         - id: aportacion-service
           uri: http://aportacion-service:8080
           predicates:
            - Path=/**

         - id: first-microservice
           uri: http://first-microservice:8080
           predicates:
            - Path=/**
            
       
   httpclient:
      connect-timeout: 1000
      response-timeout: 55s
